name: dev
on:
  push:
    branches:
      - main
      
concurrency:  
  group: dev-qa-prod
  cancel-in-progress: true

env:
  BUILD_NAME: build-${{ github.sha }}
  
jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: ${{ env.BUILD_NAME }}
          outputs: type=docker,dest=/tmp/myimage.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_NAME }}
          path: /tmp/myimage.tar
      
