name: dev
on:
  push:
    branches:
      - main
      
concurrency:  
  group: dev
  
jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        run: |
          flag_1=0
          flag_2=0
          flag_3=0
          flag_4=0
          flag_5=0

          string=$(git diff --dirstat=files,0 HEAD~1 | sed 's/^[ 0-9.]\+% //g')
          echo $string

          if [[ $string =~ "service_1" ]]; then
            flag_1=1
          fi
          if [[ $string =~ "service_2" ]]; then
            flag_2=1
          fi
          if [[ $string =~ "service_3" ]]; then
            flag_3=1
          fi
          if [[ $string =~ "service_4" ]]; then
            flag_4=1
          fi
          if [[ $string =~ "service_5" ]]; then
            flag_5=1
          fi

          echo "flag_1=$flag_1"
          echo "flag_2=$flag_2"
          echo "flag_3=$flag_3"
          echo "flag_4=$flag_4"
          echo "flag_5=$flag_5"
      
      
