name: dev
on:
  push:
    branches:
      - main
      
concurrency:  
  group: dev
  cancel-in-progress: true
  
jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_directories: ${{ steps.changed-files.outputs.all_changed_files }}  # The `dirs` doesn't exist in the outputs of changed-files@v35 action.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          dir_names: true
          # dir_names_max_depth: 2  # This is optional. If not provided, full subdirectories' paths will be provided. Use it if you need to trim the output. See docs for details: https://github.com/tj-actions/changed-files/tree/main#inputs.
          matrix: true
          path: services
          diff_relative: true

      - name: show changed files
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}

  do-stuff:
    runs-on: ubuntu-latest
    needs: [find-out-changes]
    if: ${{ needs.find-out-changes.outputs.changed_directories != '' && needs.find-out-changes.outputs.changed_directories != '[]' }}
    strategy:
      matrix: 
        directories: ${{fromJson(needs.find-out-changes.outputs.changed_directories)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: check matrix
        run: echo ${{ matrix.directories }}
        
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
    
      # - name: Build and export
      #   uses: docker/build-push-action@v6
      #   with:
      #     tags: ghcr.io/${{ github.repository }}/${{ matrix.files }}
      #     push: true    
      
      
