name: dev
on:
  push:
    branches:
      - main
      
concurrency:  
  group: dev
  cancel-in-progress: true
  
env:
  WORKING_DIR: services
jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_directories: ${{ steps.changed-files.outputs.all_changed_files }}  # The `dirs` doesn't exist in the outputs of changed-files@v35 action.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          dir_names: true
          matrix: true
          path: ${{ env.WORKING_DIR }}
          diff_relative: true

      - name: show changed files
        run: echo ${{ steps.changed-files.outputs.all_changed_files }}

  do-stuff:
    runs-on: ubuntu-latest
    needs: [find-out-changes]
    if: ${{ needs.find-out-changes.outputs.changed_directories != '' && needs.find-out-changes.outputs.changed_directories != '[]' }}
    strategy:
      matrix: 
        directories: ${{fromJson(needs.find-out-changes.outputs.changed_directories)}}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ghcr.io/${{ matrix.directories }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          file: ${{ env.WORKING_DIR }}/${{ matrix.directories }}/Dockerfile
          tags: ghcr.io/${{ matrix.directories }},${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true    
      
      
